# Generated by Django 2.0.10 on 2022-01-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school_id', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('course_name', models.CharField(max_length=150)),
                ('teacher_name', models.CharField(max_length=150)),
                ('completed', models.CharField(max_length=150)),
                ('marks', models.PositiveIntegerField()),
                ('letter_grade', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('create_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
